version: "3.8"

services:
  mysqldb:
    platform: linux/x86_64
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: exchange
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u root" ]
      interval: 30s
      timeout: 30s
      retries: 3

  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    image: currency-exchange
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/exchange
